defaults:
  seed: ${WFGY_SEED}
  stage1_tokens: ${WFGY_STAGE1_TOKENS}
  stage2_tokens: ${WFGY_STAGE2_TOKENS}
  retry_max: ${WFGY_RETRY_MAX}
  collapse_threshold: ${WFGY_COLLAPSE_THRESHOLD}
  earlystop_min_chars: ${WFGY_EARLYSTOP_MIN_CHARS}
  request_timeout_s: ${WFGY_REQUEST_TIMEOUT_S}

tasks:
  sanitize-git-repo:
    guard: strict
    retry_budget: 2
    collapse_threshold: 0.16
    notes: "Prefer short actionable steps. Avoid repo-wide destructive ops."
  extract-safely:
    guard: balanced
    retry_budget: 2
    collapse_threshold: 0.18
    notes: "Focus on boundaries, file types, and streaming plan."
  hello-world:
    guard: light
    retry_budget: 1
    collapse_threshold: 0.20
    notes: "Keep answers short and final. Do not overthink."
  generic:
    guard: balanced
    retry_budget: 2
    collapse_threshold: 0.18
