version: 1
aliases:
  strict_output: ["hello-world","simple-answer","exact-print","sanitize-git-repo","grid-pattern-transform"]
  math: ["raman","fit","curve","optimize","integral"]
  file_ops_convert: ["csv","json","yaml","xml","convert"]
  file_ops_path: ["path","mv","rename","mkdir","ls"]
  sysadmin: ["docker","compose","service","network","firewall","env"]
  interactive: ["maze","game","interactive","prompt"]
  general: ["default"]
families:
  strict_output:
    seven_step: {analyze: 0.18, plan: 0.10, tool_select: 0.02, code: 0.08, test: 0.02, format: 0.40, verify: 0.20}
    firewall: {max_system_len: 320, allow_symbols: [".",",",":",";","-","_","+","=","*","/","\\"], banned_patterns: ["explain","note:","as an ai","discussion"], whitelist_tokens: ["true","false","yes","no","0","1"]}
    dt_guard: {ngram_n: 4, max_repeat_ratio: 0.18, truncate_after: 512}
    retry: {max_attempts: 2, base_backoff_s: 1.2, jitter_s: 0.6}
    strict_output: {enabled: true, formatter: "auto", self_consistency_n: 2}
    micro_ab: {enabled: true}
    prescan: {enabled: true, seconds: 3}
    sanity: {enabled: true, steps: 1}
  math:
    seven_step: {analyze: 0.28, plan: 0.18, tool_select: 0.04, code: 0.24, test: 0.08, format: 0.06, verify: 0.12}
    firewall: {max_system_len: 640, allow_symbols: [".",",",":",";","-","_","+","=","*","/","\\","^","%","|","(",")","[","]","{","}"], banned_patterns: ["story","metaphor","explain like"], whitelist_tokens: ["sin","cos","exp","log","sqrt","argmin","argmax"]}
    dt_guard: {ngram_n: 6, max_repeat_ratio: 0.22, truncate_after: 1024}
    retry: {max_attempts: 3, base_backoff_s: 1.4, jitter_s: 0.7}
    strict_output: {enabled: true, formatter: "number", self_consistency_n: 2}
    micro_ab: {enabled: true}
    prescan: {enabled: true, seconds: 4}
    sanity: {enabled: true, steps: 1}
  file_ops_convert:
    seven_step: {analyze: 0.24, plan: 0.16, tool_select: 0.04, code: 0.20, test: 0.16, format: 0.10, verify: 0.10}
    firewall: {max_system_len: 480, allow_symbols: [".",",",":",";","-","_","+","=","*","/","\\"], banned_patterns: ["explain","opinion"], whitelist_tokens: ["csv","json","yaml","xml"]}
    dt_guard: {ngram_n: 5, max_repeat_ratio: 0.20, truncate_after: 768}
    retry: {max_attempts: 2, base_backoff_s: 1.2, jitter_s: 0.6}
    strict_output: {enabled: true, formatter: "line", self_consistency_n: 0}
    micro_ab: {enabled: false}
    prescan: {enabled: true, seconds: 3}
    sanity: {enabled: true, steps: 1}
  file_ops_path:
    seven_step: {analyze: 0.24, plan: 0.18, tool_select: 0.04, code: 0.22, test: 0.16, format: 0.08, verify: 0.08}
    firewall: {max_system_len: 480, allow_symbols: [".",",",":",";","-","_","+","=","*","/","\\"], banned_patterns: ["explain","opinion"], whitelist_tokens: ["mv","cp","mkdir","ls","find"]}
    dt_guard: {ngram_n: 5, max_repeat_ratio: 0.20, truncate_after: 768}
    retry: {max_attempts: 2, base_backoff_s: 1.2, jitter_s: 0.6}
    strict_output: {enabled: false, formatter: "line", self_consistency_n: 0}
    micro_ab: {enabled: false}
    prescan: {enabled: true, seconds: 3}
    sanity: {enabled: true, steps: 1}
  sysadmin:
    seven_step: {analyze: 0.26, plan: 0.20, tool_select: 0.04, code: 0.22, test: 0.12, format: 0.06, verify: 0.10}
    firewall: {max_system_len: 560, allow_symbols: [".",",",":",";","-","_","+","=","*","/","\\"], banned_patterns: ["explain","risky command"], whitelist_tokens: ["docker","compose","systemctl","ufw","curl","pip","apt","env"]}
    dt_guard: {ngram_n: 6, max_repeat_ratio: 0.22, truncate_after: 1024}
    retry: {max_attempts: 3, base_backoff_s: 1.6, jitter_s: 0.8}
    strict_output: {enabled: false, formatter: "line", self_consistency_n: 0}
    micro_ab: {enabled: false}
    prescan: {enabled: true, seconds: 5}
    sanity: {enabled: true, steps: 1}
  interactive:
    seven_step: {analyze: 0.22, plan: 0.20, tool_select: 0.06, code: 0.22, test: 0.12, format: 0.08, verify: 0.10}
    firewall: {max_system_len: 480, allow_symbols: [".",",",":",";","-","_","+","=","*","/","\\"], banned_patterns: ["long essay","roleplay","story"], whitelist_tokens: ["move","step","left","right","up","down","quit"]}
    dt_guard: {ngram_n: 4, max_repeat_ratio: 0.18, truncate_after: 640}
    retry: {max_attempts: 2, base_backoff_s: 1.0, jitter_s: 0.5}
    strict_output: {enabled: false, formatter: "line", self_consistency_n: 0}
    micro_ab: {enabled: false}
    prescan: {enabled: true, seconds: 2}
    sanity: {enabled: true, steps: 1}
  general:
    seven_step: {analyze: 0.22, plan: 0.16, tool_select: 0.04, code: 0.22, test: 0.12, format: 0.12, verify: 0.12}
    firewall: {max_system_len: 480, allow_symbols: [".",",",":",";","-","_","+","=","*","/","\\"], banned_patterns: ["essay","story"], whitelist_tokens: []}
    dt_guard: {ngram_n: 5, max_repeat_ratio: 0.20, truncate_after: 768}
    retry: {max_attempts: 2, base_backoff_s: 1.2, jitter_s: 0.6}
    strict_output: {enabled: false, formatter: "line", self_consistency_n: 0}
    micro_ab: {enabled: false}
    prescan: {enabled: true, seconds: 3}
    sanity: {enabled: true, steps: 1}
